#!/usr/bin/env node
/*
  sl-create utility generator
  Usage:
    - npm run sl-create:util utilName
*/

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getPaths, parseNameFromArgs, safeName, toLowerCamelCase, toPascalCase } from "./utils.mjs";

function createUtilityFile(exportName) {
  const fnName = toLowerCamelCase(exportName);
  return `// Auto-generated by sl-cli\n\nexport function ${fnName}() {\n  return null\n}\n\nexport default ${fnName}\n`;
}

async function main() {
  const { name } = parseNameFromArgs({ flag: "-u" });
  if (!name) {
    console.error("Error: Missing utility name. Use: npm run sl-create:util utilName");
    process.exit(1);
  }

  const cleaned = safeName(name);
  if (!cleaned) {
    console.error("Error: Invalid utility name.");
    process.exit(1);
  }

  const exportConstName = toPascalCase(cleaned);
  const fileBase = toLowerCamelCase(exportConstName);

  const { utilitiesDir } = getPaths();
  mkdirSync(utilitiesDir, { recursive: true });

  const filePath = resolve(utilitiesDir, `${fileBase}.ts`);
  if (existsSync(filePath)) {
    console.error(`Error: Utility file already exists at ${filePath}`);
    process.exit(1);
  }

  writeFileSync(filePath, createUtilityFile(exportConstName), "utf8");

  console.log(`\nCreated utility:`);
  console.log(`- ${filePath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
